(function(){
'use strict';
const $=s=>document.querySelector(s);
let session=null,user=null,member=null,jobs=[],selected=null,intake=null,assets=[],messages=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const statusLabel=v=>String(v||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const priceLabel=item=>{const m=item?.price_mode||'hidden';if(m==='free')return'Free';if(m==='quote')return'Contact for quote';if(m==='hidden')return'No public price';if(m==='starting')return`Starting at ${item.price||'—'}`;return item?.price||'—';};
function kv(label,value){return `<div><small>${esc(label)}</small><strong>${esc(value||'—')}</strong></div>`;}
function alertBox(type,message){const n=$('#dt-alert');if(!n)return;n.className=`dw-alert show ${type}`;n.textContent=message;}
async function requireDesigner(){const {data,error}=await supabaseClient.auth.getSession();if(error)throw error;session=data?.session||null;user=session?.user||null;if(!user){location.href=liwUrl('login.html');return false;}const {data:m,error:me}=await supabaseClient.from('designer_team_members').select('*').eq('user_id',user.id).maybeSingle();if(me)throw me;if(!m?.is_active){$('#dt-loading').innerHTML='<i data-lucide="shield-alert" size="30"></i><h2>Designer access required.</h2><p>This workspace is only for active LIW design team members.</p><a class="dw-btn navy" href="dashboard.html">Back to dashboard</a>';window.lucide?.createIcons?.();return false;}member=m;$('#dt-member-name').textContent=m.display_name||user.email;$('#dt-member-role').textContent=m.role_title||'Designer';return true;}
async function loadJobs(){const {data,error}=await supabaseClient.from('designer_orders').select('*').eq('assigned_to',user.id).order('created_at',{ascending:false});if(error)throw error;jobs=data||[];renderJobs();}
function renderJobs(){const wrap=$('#dt-job-list');if(!wrap)return;wrap.innerHTML=jobs.length?jobs.map(j=>`<button class="dt-job ${selected?.id===j.id?'active':''}" type="button" data-id="${esc(j.id)}"><strong>${esc(j.order_number)} · ${esc(j.service_name)}</strong><span><b>${esc(statusLabel(j.workflow_status))}</b><em>${Number(j.revisions_used||0)}/${Number(j.revision_limit||0)} rev</em></span><span><b>${esc(j.customer_email||'Customer')}</b><em>${j.card_id?'Card ready':'No card yet'}</em></span></button>`).join(''):'<div class="dt-empty"><p>No design jobs are assigned to you right now.</p></div>';wrap.querySelectorAll('[data-id]').forEach(b=>b.addEventListener('click',()=>openJob(b.dataset.id)));}
async function openJob(id){selected=jobs.find(j=>j.id===id)||null;if(!selected)return;renderJobs();$('#dt-empty').hidden=true;$('#dt-work').hidden=false;const [ir,ar,mr]=await Promise.all([supabaseClient.from('designer_intakes').select('*').eq('order_id',id).maybeSingle(),supabaseClient.from('designer_order_assets').select('*').eq('order_id',id).order('created_at'),supabaseClient.from('designer_order_messages').select('*').eq('order_id',id).order('created_at')]);for(const r of [ir,ar,mr])if(r.error)throw r.error;intake=ir.data;assets=ar.data||[];messages=mr.data||[];renderJob();}
function offerCards(title,items){if(!Array.isArray(items)||!items.length)return'';return `<section class="dt-section"><h3>${esc(title)}</h3><div class="dt-offers">${items.map(item=>{const x=typeof item==='string'?{name:item}:item||{};return `<article class="dt-offer"><div class="dt-offer-head"><strong>${esc(x.name||x.title||'Untitled')}</strong><span>${esc(priceLabel(x))}</span></div>${x.description?`<p>${esc(x.description)}</p>`:''}${x.link?`<p>${esc(x.link)}</p>`:''}</article>`}).join('')}</div></section>`;}
function renderJob(){if(!selected)return;$('#dt-title').textContent=`${selected.order_number} · ${selected.service_name}`;$('#dt-subtitle').textContent=intake?.business_name||intake?.contact_name||selected.customer_email||'Customer project';$('#dt-status').textContent=statusLabel(selected.workflow_status);const edit=$('#dt-open-editor');if(selected.card_id){edit.hidden=false;edit.href=`editor.html?id=${encodeURIComponent(selected.card_id)}&designer_order=${encodeURIComponent(selected.id)}`;}else edit.hidden=true;const review=$('#dt-submit-review'),state=$('#dt-review-state');const canSubmit=Boolean(selected.card_id&&['in_design','revision_requested'].includes(selected.workflow_status));if(review)review.hidden=!canSubmit;if(state){const waiting=['customer_review','approved','publishing','completed'].includes(selected.workflow_status);state.hidden=!waiting;state.textContent=selected.workflow_status==='customer_review'?'Submitted · waiting for customer review':selected.workflow_status==='approved'?'Customer approved':selected.workflow_status==='publishing'?'Approved · publishing':selected.workflow_status==='completed'?'Project completed':'';}$('#dt-brief').innerHTML=intake?`<section class="dt-section"><h3>Business & card copy</h3><div class="dt-kv">${[kv('Name',intake.contact_name),kv('Business',intake.business_name),kv('Title',intake.job_title),kv('Email',intake.contact_email),kv('Phone',intake.phone),kv('Website',intake.website),kv('Address',intake.business_address),kv('Card bio',intake.biography||intake.business_description)].join('')}</div></section><section class="dt-section"><h3>Goal & visual direction</h3><div class="dt-kv">${[kv('Business description',intake.business_description),kv('Main goal',intake.primary_goal),kv('Audience',intake.target_audience),kv('Style',intake.preferred_style||'LIW choice'),kv('Template',intake.preferred_template||'LIW choice'),kv('Brand colors',Array.isArray(intake.brand_colors)&&intake.brand_colors.length?intake.brand_colors.join(' · '):'LIW choice'),kv('Brand notes',intake.color_notes)].join('')}</div></section><section class="dt-section"><h3>Links & actions</h3><div class="dt-kv">${[kv('Booking',intake.booking_url),kv('Payment',intake.payment_url),kv('Socials',Array.isArray(intake.social_links)?intake.social_links.map(s=>typeof s==='string'?s:`${s.platform}: ${s.value}`).join(' · '):''),kv('Special requests',intake.special_requests)].join('')}</div></section>${offerCards('Services',intake.services)}${offerCards('Products',intake.products)}`:'<div class="dt-empty"><p>No intake is available yet.</p></div>';renderAssets();renderMessages();window.lucide?.createIcons?.();}
async function openAsset(asset){const {data,error}=await supabaseClient.storage.from('designer-assets').createSignedUrl(asset.storage_path,300);if(error)return alertBox('error',error.message);window.open(data.signedUrl,'_blank','noopener');}
function renderAssets(){const wrap=$('#dt-assets');if(!wrap)return;wrap.innerHTML=assets.length?assets.map(a=>`<div class="dt-asset"><i data-lucide="${a.mime_type==='application/pdf'?'file-text':'image'}" size="16"></i><button type="button" data-asset="${esc(a.id)}"><strong>${esc(a.original_name)}</strong><small>${esc(String(a.asset_type||'asset').replaceAll('_',' '))}</small></button><i data-lucide="external-link" size="14"></i></div>`).join(''):'<p class="dw-admin-empty-note">No private assets uploaded.</p>';wrap.querySelectorAll('[data-asset]').forEach(b=>b.addEventListener('click',()=>{const a=assets.find(x=>x.id===b.dataset.asset);if(a)openAsset(a)}));}
function renderMessages(){const wrap=$('#dt-notes');if(!wrap)return;const internal=messages.filter(m=>m.is_internal);wrap.innerHTML=internal.length?internal.map(m=>`<div class="dw-message dw-internal"><div class="dw-message-head"><strong>${m.sender_role==='designer'?'Designer note':'LIW note'}</strong><time>${new Date(m.created_at).toLocaleString()}</time></div><p>${esc(m.message)}</p></div>`).join(''):'<div class="dw-message"><p>No internal production notes yet.</p></div>';}
async function addNote(e){e.preventDefault();if(!selected)return;const input=$('#dt-note'),message=input.value.trim();if(!message)return;const btn=$('#dt-note-submit');btn.disabled=true;const {data,error}=await supabaseClient.from('designer_order_messages').insert({order_id:selected.id,user_id:user.id,sender_role:'designer',message_type:'note',message,is_internal:true}).select('*').single();if(error){alertBox('error',error.message);btn.disabled=false;return;}messages.push(data);input.value='';renderMessages();btn.disabled=false;alertBox('success','Internal production note saved.');}
async function notifyReview(orderId){if(!session?.access_token)return;const response=await fetch(`${LIW_CONFIG.supabaseUrl}/functions/v1/notify-designer-order`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':LIW_CONFIG.supabaseKey},body:JSON.stringify({orderId,eventKey:'customer_review'})});if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Customer review notification could not be sent');}}
async function submitReview(){if(!selected)return;const btn=$('#dt-submit-review');if(!confirm('Submit this design for customer review? You can continue editing only if LIW/customer requests revisions.'))return;btn.disabled=true;try{const {data,error}=await supabaseClient.rpc('designer_submit_customer_review',{p_order_id:selected.id,p_note:'Assigned designer completed the build and submitted it for customer review.'});if(error)throw error;selected=data;const idx=jobs.findIndex(j=>j.id===selected.id);if(idx>=0)jobs[idx]=selected;try{await notifyReview(selected.id);}catch(notificationError){console.warn('Designer review notification:',notificationError);}await openJob(selected.id);alertBox('success','Design submitted for customer review. LIW and the customer can now review it.');}catch(e){alertBox('error',e.message||'Could not submit this design for review.');btn.disabled=false;}}
async function init(){window.lucide?.createIcons?.();try{if(!await requireDesigner())return;await loadJobs();$('#dt-loading').hidden=true;$('#dt-app').hidden=false;const requested=new URLSearchParams(location.search).get('order');const first=requested&&jobs.some(j=>j.id===requested)?requested:jobs[0]?.id;if(first)await openJob(first);$('#dt-note-form')?.addEventListener('submit',addNote);$('#dt-submit-review')?.addEventListener('click',submitReview);}catch(e){console.error(e);$('#dt-loading').hidden=true;alertBox('error',e.message||'Could not open designer workspace.');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
