(function(){
'use strict';
const $=s=>document.querySelector(s), params=new URLSearchParams(location.search);
let session=null,user=null,order=null,messages=[],history=[],linkedCardUrl=null;
const labels={awaiting_intake:'Awaiting intake',intake_submitted:'Intake submitted',in_design:'In design',customer_review:'Ready for review',revision_requested:'Revision requested',approved:'Approved',publishing:'Publishing',completed:'Completed',on_hold:'On hold',canceled:'Canceled'};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
const fmtTime=v=>v?new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'';
function alertBox(type,message){const n=$('#dw-alert');if(!n)return;n.className=`dw-alert show ${type}`;n.textContent=message;}
function setText(sel,val){const n=$(sel);if(n)n.textContent=val||'—';}
async function notifyDesigner(eventKey){if(!session?.access_token||!order?.id)return;const res=await fetch(`${LIW_CONFIG.supabaseUrl}/functions/v1/notify-designer-order`,{method:'POST',headers:{'Content-Type':'application/json','Authorization':`Bearer ${session.access_token}`,'apikey':LIW_CONFIG.supabaseKey},body:JSON.stringify({orderId:order.id,eventKey})});if(!res.ok){const data=await res.json().catch(()=>({}));throw new Error(data.error||'Designer notification could not be sent');}}
function stageIndex(status){if(status==='awaiting_intake')return 1;if(status==='intake_submitted')return 2;if(['in_design','revision_requested'].includes(status))return 2;if(['customer_review','approved'].includes(status))return 3;if(status==='publishing')return 4;if(status==='completed')return 5;return 2;}
function renderProgress(){const idx=stageIndex(order.workflow_status);[...$('#dw-order-progress').children].forEach((node,i)=>{const n=i+1;node.classList.toggle('complete',n<idx||order.workflow_status==='completed');node.classList.toggle('active',n===idx&&order.workflow_status!=='completed')});}
function nextStep(){switch(order.workflow_status){case'awaiting_intake':return '<strong>Next:</strong> complete your intake so LIW can begin.';case'intake_submitted':return '<strong>Next:</strong> LIW is reviewing your intake before production starts.';case'in_design':return '<strong>In production:</strong> your designer is building the card.';case'customer_review':return '<strong>Your turn:</strong> review the card and approve it or request a revision.';case'revision_requested':return '<strong>Revision received:</strong> LIW is working through your requested changes.';case'approved':return '<strong>Approved:</strong> LIW is preparing the final publish step.';case'publishing':return '<strong>Publishing:</strong> final checks are underway.';case'completed':return '<strong>Complete:</strong> your finished LIW card is ready.';case'on_hold':return '<strong>On hold:</strong> check the message thread for what is needed.';case'canceled':return '<strong>Canceled:</strong> contact LIW support if you have questions.';default:return 'Your project is being updated.'}}
function renderTimeline(){const stages=[['Payment received','Your designer service payment was confirmed.','paid'],['Intake submitted','Your business details and assets were sent to LIW.','intake'],['Design in progress','LIW is building and styling your card.','design'],['Customer review','You approve the design or request an included revision.','review'],['Completed','Final card is approved and ready to share.','complete']];const idx=stageIndex(order.workflow_status);$('#dw-timeline').innerHTML=stages.map((s,i)=>{const n=i+1,done=n<idx||order.workflow_status==='completed',current=n===idx&&order.workflow_status!=='completed';return `<div class="dw-timeline-row ${done?'done':''} ${current?'current':''}"><span class="dw-timeline-dot"><i data-lucide="${done?'check':current?'clock-3':'circle'}" size="14"></i></span><div><strong>${s[0]}</strong><small>${s[1]}</small></div></div>`}).join('');window.lucide?.createIcons?.();}
function renderActions(){const wrap=$('#dw-primary-actions');wrap.innerHTML='';if(order.workflow_status==='awaiting_intake'){wrap.innerHTML=`<a class="dw-btn primary" href="designer-intake.html?order=${encodeURIComponent(order.id)}">Complete intake <i data-lucide="arrow-right" size="16"></i></a>`}else if(order.workflow_status==='completed'&&linkedCardUrl){wrap.innerHTML=`<a class="dw-btn primary" href="${linkedCardUrl}" target="_blank" rel="noopener">Open finished card <i data-lucide="external-link" size="16"></i></a>`}window.lucide?.createIcons?.();}
async function cardUrl(){if(!order.card_id)return null;const {data,error}=await supabaseClient.from('digital_cards').select('slug,status').eq('id',order.card_id).maybeSingle();if(error||!data)return null;return `card.html?slug=${encodeURIComponent(data.slug)}`;}
async function renderPreview(){linkedCardUrl=await cardUrl();const panel=$('#dw-preview-panel');if(!linkedCardUrl){panel.hidden=true;renderActions();return}panel.hidden=false;$('#dw-card-frame').src=`${linkedCardUrl}&designerReview=1`;$('#dw-open-card').href=linkedCardUrl;const review=$('#dw-review-box');review.hidden=order.workflow_status!=='customer_review';if(order.workflow_status==='customer_review'){const left=Math.max(0,(order.revision_limit||0)-(order.revisions_used||0));$('#dw-review-copy').textContent=`You have ${left} included revision${left===1?'':'s'} remaining. Approve the design when you are satisfied.`;$('#dw-revision-button').disabled=left<=0;}renderActions();window.lucide?.createIcons?.();}
function renderMessages(){const wrap=$('#dw-thread');if(!messages.length){wrap.innerHTML='<div class="dw-message"><p>No messages yet. Updates from LIW will appear here.</p></div>';return}wrap.innerHTML=messages.map(m=>`<div class="dw-message ${m.sender_role==='customer'?'mine':''}"><div class="dw-message-head"><strong>${m.sender_role==='customer'?'You':m.sender_role==='system'?'LIW Update':'LIW Design Team'}</strong><time>${fmtTime(m.created_at)}</time></div><p>${esc(m.message)}</p></div>`).join('');}
function renderOrder(){setText('#dw-order-number',order.order_number);setText('#dw-status-badge',labels[order.workflow_status]||order.workflow_status);setText('#dw-service',order.service_name||order.service_key);setText('#dw-plan',order.selected_plan_name||order.selected_plan_key||'Current LIW plan');setText('#dw-domain',order.domain_mode==='buy'?(order.domain_name||'Custom domain'):order.domain_mode==='own'?(order.domain_name||'Existing domain'):'LIW card link');setText('#dw-revisions',`${order.revisions_used||0} used · ${Math.max(0,(order.revision_limit||0)-(order.revisions_used||0))} remaining`);setText('#dw-created',fmtDate(order.created_at));$('#dw-next-step').innerHTML=nextStep();renderProgress();renderTimeline();renderActions();renderPreview();}
async function reload(){const id=order?.id||params.get('id');if(!id)throw new Error('Designer order ID is missing.');const [{data:o,error:oe},{data:m,error:me},{data:h,error:he}]=await Promise.all([supabaseClient.from('designer_orders').select('*').eq('id',id).maybeSingle(),supabaseClient.from('designer_order_messages').select('*').eq('order_id',id).order('created_at'),supabaseClient.from('designer_order_status_history').select('*').eq('order_id',id).order('created_at')]);if(oe)throw oe;if(me)throw me;if(he)throw he;if(!o)throw new Error('Designer order not found.');order=o;messages=m||[];history=h||[];renderOrder();renderMessages();}
async function sendMessage(e){e.preventDefault();const input=$('#dw-message-input'),message=input.value.trim();if(!message)return;const btn=e.submitter;btn.disabled=true;try{const {error}=await supabaseClient.from('designer_order_messages').insert({order_id:order.id,user_id:user.id,sender_role:'customer',message_type:'message',message,is_internal:false});if(error)throw error;input.value='';await reload();}catch(err){alertBox('error',err.message||'Could not send message.')}finally{btn.disabled=false}}
async function review(decision){const notes=$('#dw-review-notes').value.trim();if(decision==='revision_requested'&&!notes){alertBox('error','Tell us exactly what you would like changed before requesting a revision.');return}const btn=decision==='approved'?$('#dw-approve-button'):$('#dw-revision-button');btn.disabled=true;try{const {data,error}=await supabaseClient.rpc('submit_designer_review',{p_order_id:order.id,p_decision:decision,p_notes:notes||null});if(error)throw error;order=data;$('#dw-review-notes').value='';alertBox('success',decision==='approved'?'Design approved. LIW will complete the publish process.':'Revision request sent to the LIW design team.');try{await notifyDesigner(decision==='approved'?'approved':'revision_requested');}catch(notificationError){console.warn('Designer review notification failed:',notificationError);}await reload();}catch(err){alertBox('error',err.message||'Could not submit your review.')}finally{btn.disabled=false}}
async function init(){window.lucide?.createIcons?.();const r=await supabaseClient.auth.getSession();session=r.data.session;user=session?.user||null;if(!user){location.href=liwUrl('login.html');return}try{await reload();$('#dw-order-loading').hidden=true;$('#dw-order-app').hidden=false;$('#dw-message-form').addEventListener('submit',sendMessage);$('#dw-approve-button').addEventListener('click',()=>review('approved'));$('#dw-revision-button').addEventListener('click',()=>review('revision_requested'));if(params.get('submitted'))alertBox('success','Your intake was submitted successfully.');window.lucide?.createIcons?.();}catch(err){console.error(err);$('#dw-order-loading').hidden=true;alertBox('error',err.message||'Could not load this designer order.')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();