(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const params=new URLSearchParams(location.search);
let session=null,user=null,order=null,intake=null,assets=[],saveTimer=null,saving=false;
const fields=['contact_name','business_name','job_title','contact_email','phone','website','business_address','business_description','primary_goal','target_audience','preferred_style','preferred_template','color_notes','booking_url','payment_url','special_requests'];
const repeatKeys=['social_links','extra_links','services','products','inspiration_urls'];
const editableStatuses=new Set(['awaiting_intake','intake_submitted','on_hold']);
function alertBox(type,message){const n=$('#dw-alert');if(!n)return;n.className=`dw-alert show ${type}`;n.textContent=message;}
function clearAlert(){const n=$('#dw-alert');if(n)n.className='dw-alert';}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(cents){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(cents||0)/100)}
function prettyStatus(s){return ({awaiting_intake:'Awaiting intake',intake_submitted:'Intake submitted',in_design:'In design',customer_review:'Ready for review',revision_requested:'Revision requested',approved:'Approved',publishing:'Publishing',completed:'Completed',on_hold:'On hold',canceled:'Canceled'})[s]||s;}
function cleanUrl(v){const x=String(v||'').trim();if(!x)return '';return /^https?:\/\//i.test(x)?x:`https://${x}`;}
async function requireSession(){const r=await supabaseClient.auth.getSession();session=r.data.session;user=session?.user||null;if(!user){try{sessionStorage.setItem('liw_designer_return_url',location.href)}catch(_){ }location.href=liwUrl('login.html');return false;}return true;}
async function resolveOrder(){const orderId=params.get('order');const sessionId=params.get('session_id');
 if(orderId){const {data,error}=await supabaseClient.from('designer_orders').select('*').eq('id',orderId).maybeSingle();if(error)throw error;return data;}
 if(sessionId){for(let attempt=0;attempt<8;attempt++){const {data:purchase,error:pe}=await supabaseClient.from('one_time_orders').select('id,status,offer_key').eq('stripe_checkout_session_id',sessionId).maybeSingle();if(pe)throw pe;if(purchase){const {data,error}=await supabaseClient.from('designer_orders').select('*').eq('one_time_order_id',purchase.id).maybeSingle();if(error)throw error;if(data)return data;}await new Promise(r=>setTimeout(r,attempt<3?700:1300));}throw new Error('Payment was received but the designer order is still being prepared. Refresh this page in a moment.');}
 const {data,error}=await supabaseClient.from('designer_orders').select('*').eq('user_id',user.id).order('created_at',{ascending:false}).limit(1).maybeSingle();if(error)throw error;return data;}
function repeatRow(key,value=''){const row=document.createElement('div');row.className='dw-repeat-row';row.innerHTML=`<input class="dw-input" maxlength="400" value="${esc(value)}" placeholder="${key==='services'?'Service name or description':key==='products'?'Product name or link':'https://'}"><button type="button" aria-label="Remove"><i data-lucide="trash-2" size="15"></i></button>`;row.querySelector('button').addEventListener('click',()=>{row.remove();queueSave();});row.querySelector('input').addEventListener('input',queueSave);return row;}
function setRepeat(key,values){const wrap=$(`#${key}`);if(!wrap)return;wrap.innerHTML='';const list=Array.isArray(values)?values:(values&&typeof values==='object'?Object.values(values):[]);(list.length?list:['']).forEach(v=>wrap.appendChild(repeatRow(key,String(v||''))));}
function getRepeat(key){return [...$(`#${key}`)?.querySelectorAll('input')||[]].map(i=>i.value.trim()).filter(Boolean);}
function bindRepeats(){$$('[data-add-repeat]').forEach(btn=>btn.addEventListener('click',()=>{const key=btn.dataset.addRepeat;const wrap=$(`#${key}`);wrap?.appendChild(repeatRow(key,''));wrap?.lastElementChild?.querySelector('input')?.focus();window.lucide?.createIcons?.();}));}
function bindColors(){for(let i=1;i<=3;i++){const p=$(`#brand_color_${i}_picker`),t=$(`#brand_color_${i}`);p?.addEventListener('input',()=>{t.value=p.value;queueSave();});t?.addEventListener('input',()=>{if(/^#[0-9a-f]{6}$/i.test(t.value))p.value=t.value;queueSave();});}}
function payload(){const out={order_id:order.id,user_id:user.id,terms_ack:Boolean($('#terms_ack')?.checked)};fields.forEach(k=>out[k]=$(`#${k}`)?.value.trim()||null);out.website=cleanUrl(out.website);out.booking_url=cleanUrl(out.booking_url);out.payment_url=cleanUrl(out.payment_url);out.brand_colors=[$('#brand_color_1')?.value,$('#brand_color_2')?.value,$('#brand_color_3')?.value].filter(v=>/^#[0-9a-f]{6}$/i.test(v||''));repeatKeys.forEach(k=>out[k]=getRepeat(k));return out;}
function setSaveState(text){const n=$('#dw-save-state');if(n)n.textContent=text;}
async function saveDraft(opts={}){if(!order||saving||!editableStatuses.has(order.workflow_status))return;saving=true;if(!opts.silent)setSaveState('Saving…');try{const data=payload();const {data:saved,error}=await supabaseClient.from('designer_intakes').upsert(data,{onConflict:'order_id'}).select('*').single();if(error)throw error;intake=saved;setSaveState(`Saved ${new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}`);if(!opts.silent)window.toast?.('Designer intake saved');}catch(e){console.error(e);setSaveState('Save failed');if(!opts.silent)alertBox('error',e.message||'Could not save your intake.');}finally{saving=false;}}
function queueSave(){clearTimeout(saveTimer);setSaveState('Unsaved changes');saveTimer=setTimeout(()=>saveDraft({silent:true}),1200);}
function fillForm(data){fields.forEach(k=>{const el=$(`#${k}`);if(el&&data?.[k]!=null)el.value=data[k]});const colors=Array.isArray(data?.brand_colors)?data.brand_colors:[];for(let i=1;i<=3;i++){const v=colors[i-1]||['#0b1438','#d4a84f','#ffffff'][i-1];const t=$(`#brand_color_${i}`),p=$(`#brand_color_${i}_picker`);if(t)t.value=v;if(p&&/^#[0-9a-f]{6}$/i.test(v))p.value=v;}repeatKeys.forEach(k=>setRepeat(k,data?.[k]));if($('#terms_ack'))$('#terms_ack').checked=Boolean(data?.terms_ack);}
function renderOrder(){setText('#dw-order-number',order.order_number);setText('#dw-summary-service',order.service_name||order.service_key);setText('#dw-summary-plan',order.selected_plan_name||order.selected_plan_key||'Current LIW plan');setText('#dw-summary-domain',order.domain_mode==='buy'?(order.domain_name||'Custom domain'):order.domain_mode==='own'?(order.domain_name||'Existing domain'):'LIW card link');setText('#dw-summary-revisions',String(order.revision_limit||0));}
function setText(sel,val){const n=$(sel);if(n)n.textContent=val||'—';}
function inferAssetType(file){const n=file.name.toLowerCase();if(file.type==='application/pdf')return 'brand_guide';if(/logo/.test(n))return 'logo';if(/head|profile|portrait/.test(n))return 'profile_photo';if(/cover|banner|hero/.test(n))return 'cover_photo';if(/inspir|example|reference/.test(n))return 'inspiration';return 'other';}
function safeName(name){return String(name||'file').replace(/[^a-zA-Z0-9._-]+/g,'-').replace(/-+/g,'-').slice(-120)}
async function uploadFiles(fileList){const allowed=new Set(['image/jpeg','image/png','image/webp','application/pdf']);for(const file of [...fileList]){if(!allowed.has(file.type)){alertBox('error',`${file.name}: unsupported file type.`);continue}if(file.size>10*1024*1024){alertBox('error',`${file.name}: file is larger than 10 MB.`);continue}const path=`${user.id}/${order.id}/${crypto.randomUUID()}-${safeName(file.name)}`;setSaveState(`Uploading ${file.name}…`);const {error:ue}=await supabaseClient.storage.from('designer-assets').upload(path,file,{cacheControl:'3600',upsert:false});if(ue){alertBox('error',`Could not upload ${file.name}: ${ue.message}`);continue}const row={order_id:order.id,user_id:user.id,asset_type:inferAssetType(file),storage_path:path,original_name:file.name,mime_type:file.type,size_bytes:file.size};const {data,error}=await supabaseClient.from('designer_order_assets').insert(row).select('*').single();if(error){await supabaseClient.storage.from('designer-assets').remove([path]);alertBox('error',`Could not attach ${file.name}: ${error.message}`);continue}assets.push(data);renderAssets();}setSaveState('Uploads saved');}
async function removeAsset(asset){if(!confirm(`Remove ${asset.original_name}?`))return;const {error:se}=await supabaseClient.storage.from('designer-assets').remove([asset.storage_path]);if(se)return alertBox('error',se.message);const {error}=await supabaseClient.from('designer_order_assets').delete().eq('id',asset.id);if(error)return alertBox('error',error.message);assets=assets.filter(a=>a.id!==asset.id);renderAssets();}
async function openAsset(asset){const {data,error}=await supabaseClient.storage.from('designer-assets').createSignedUrl(asset.storage_path,120);if(error)return alertBox('error',error.message);window.open(data.signedUrl,'_blank','noopener');}
function renderAssets(){const wrap=$('#dw-assets');if(!wrap)return;wrap.innerHTML='';assets.forEach(asset=>{const row=document.createElement('div');row.className='dw-asset';row.innerHTML=`<span class="dw-asset-icon"><i data-lucide="${asset.mime_type==='application/pdf'?'file-text':'image'}" size="16"></i></span><button type="button" style="border:0;background:transparent;text-align:left;min-width:0;cursor:pointer"><strong>${esc(asset.original_name)}</strong><small>${esc(asset.asset_type.replaceAll('_',' '))} · ${asset.size_bytes?Math.max(1,Math.round(asset.size_bytes/1024))+' KB':''}</small></button><button type="button" aria-label="Remove"><i data-lucide="trash-2" size="15"></i></button>`;const bs=row.querySelectorAll('button');bs[0].addEventListener('click',()=>openAsset(asset));bs[1].addEventListener('click',()=>removeAsset(asset));wrap.appendChild(row)});window.lucide?.createIcons?.();}
function bindUpload(){const input=$('#dw-file-input'),zone=$('#dw-upload-zone');input?.addEventListener('change',e=>{uploadFiles(e.target.files);e.target.value=''});['dragenter','dragover'].forEach(ev=>zone?.addEventListener(ev,e=>{e.preventDefault();zone.classList.add('drag')}));['dragleave','drop'].forEach(ev=>zone?.addEventListener(ev,e=>{e.preventDefault();zone.classList.remove('drag')}));zone?.addEventListener('drop',e=>uploadFiles(e.dataTransfer.files));}
function validate(){const d=payload();const missing=[];if(!d.contact_name)missing.push('your name');if(!d.business_name)missing.push('business / brand name');if(!d.contact_email)missing.push('email');if(!d.business_description)missing.push('business description');if(!d.primary_goal)missing.push('main card goal');if(!d.terms_ack)missing.push('confirmation checkbox');if(missing.length){alertBox('error',`Before submitting, complete: ${missing.join(', ')}.`);return false}return true;}
async function submit(event){event.preventDefault();clearAlert();if(!validate())return;const btn=$('#dw-submit-button');btn.disabled=true;try{await saveDraft({silent:true});const {data,error}=await supabaseClient.rpc('submit_designer_intake',{p_order_id:order.id});if(error)throw error;order=data;alertBox('success','Intake submitted. LIW can now begin your design.');setTimeout(()=>location.href=liwUrl(`designer-order.html?id=${encodeURIComponent(order.id)}&submitted=1`),650);}catch(e){console.error(e);alertBox('error',e.message||'Could not submit your intake.');btn.disabled=false;}}
async function init(){window.lucide?.createIcons?.();if(!await requireSession())return;try{order=await resolveOrder();if(!order)throw new Error('No designer order was found for this account.');if(order.payment_status!=='paid')throw new Error('This designer order is not marked paid yet.');if(!editableStatuses.has(order.workflow_status)){location.href=liwUrl(`designer-order.html?id=${encodeURIComponent(order.id)}`);return}const [{data:i,error:ie},{data:a,error:ae}]=await Promise.all([supabaseClient.from('designer_intakes').select('*').eq('order_id',order.id).maybeSingle(),supabaseClient.from('designer_order_assets').select('*').eq('order_id',order.id).order('created_at')]);if(ie)throw ie;if(ae)throw ae;intake=i||{contact_email:order.customer_email||user.email||''};assets=a||[];fillForm(intake);renderOrder();renderAssets();bindRepeats();bindColors();bindUpload();fields.forEach(k=>$(`#${k}`)?.addEventListener('input',queueSave));$('#terms_ack')?.addEventListener('change',queueSave);$('#dw-save-button')?.addEventListener('click',()=>saveDraft());$('#dw-intake-form')?.addEventListener('submit',submit);$('#dw-loading').hidden=true;$('#dw-intake-app').hidden=false;window.lucide?.createIcons?.();}catch(e){console.error(e);$('#dw-loading').hidden=true;alertBox('error',e.message||'Could not load your designer order.');const box=document.createElement('div');box.className='dw-card dw-empty';box.innerHTML='<i data-lucide="circle-alert" size="28"></i><h2>We could not open this intake.</h2><p>Make sure you are signed into the same LIW account used for the purchase.</p><a class="dw-btn navy" href="designer-orders.html">View my designer orders</a>';$('.dw-shell')?.appendChild(box);window.lucide?.createIcons?.();}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();