-- Staging Super Admin plan override support.
-- Additive/backward-compatible: existing billing stays in subscriptions.plan_key/status
-- unless an explicit admin override is active.

alter table public.subscriptions
  add column if not exists billing_plan_key text,
  add column if not exists billing_status text,
  add column if not exists admin_override_plan_key text,
  add column if not exists admin_override_reason text,
  add column if not exists admin_override_by text,
  add column if not exists admin_override_at timestamptz;

update public.subscriptions
set billing_plan_key = coalesce(billing_plan_key, plan_key),
    billing_status = coalesce(billing_status, status)
where stripe_subscription_id is not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'subscriptions_admin_override_plan_key_check'
  ) then
    alter table public.subscriptions
      add constraint subscriptions_admin_override_plan_key_check
      check (admin_override_plan_key is null or admin_override_plan_key in ('starter','lite','plus','pro','agency'));
  end if;
end $$;

create table if not exists public.admin_plan_change_history (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  previous_plan_key text not null,
  new_plan_key text not null,
  action text not null check (action in ('override','restore')),
  reason text,
  changed_by text not null,
  changed_at timestamptz not null default now()
);

alter table public.admin_plan_change_history enable row level security;

create index if not exists admin_plan_change_history_user_time_idx
  on public.admin_plan_change_history(user_id, changed_at desc);

create or replace function public.preserve_admin_plan_override()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.admin_override_plan_key is not null
     and new.admin_override_plan_key is not distinct from old.admin_override_plan_key then
    if new.plan_key is distinct from old.plan_key then
      new.billing_plan_key := new.plan_key;
    end if;
    if new.status is distinct from old.status then
      new.billing_status := new.status;
    end if;
    new.plan_key := old.admin_override_plan_key;
    new.status := 'active';
  end if;
  return new;
end;
$$;

drop trigger if exists subscriptions_preserve_admin_plan_override on public.subscriptions;
create trigger subscriptions_preserve_admin_plan_override
before update on public.subscriptions
for each row execute function public.preserve_admin_plan_override();
